=== ep-infosec/33_apache_openoffice/main/xmerge/java/xmerge/converter.dtd
<!--***********************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 ***********************************************************-->



<!-- converter.dtd

     Author: Brian Cameron

     This DTD file is provided for documentation and development
     purposes, the converter does not actually validate the
     converter.xml files that it processes.  Plug-ins will not
     work properly, though, if the converter.xml does not
     conform to this DTD specification.  -->

<!-- The root node, converters, must contain one or more
     converter nodes, each corresponds to a converter plug-in. -->

<!ELEMENT converters (converter)+>

<!-- The converter node must contain two elements:
     type    - The convert-from mime-type.
     version - The version of the plug-in.

     Each converter node must contain these child nodes:
     converter-display-name     - Name of the converter
     converter-class-impl       - The PluginFactory implementation for
                                  the plugin
     converter-targets          - Can be one or more of these nodes.  Each
                                  contains only a "type" element.  This
                                  "type" element specifies the convert-to
                                  mime-type.
			      
     Each converter node may contain these child nodes:
     converter-description      - Descriptive description of the plug-in.
     converter-vendor           - Plug-in vendor name
     converter-xslt-serialize   - The URL of the xsl stylesheet for
                                  serialization.  This stylesheet must
                                  exist if the xslt plugin implementation
                                  is to be used.  It is assumed that the
                                  plug-in specified via converter-class-impl
                                  will make use of this value.
     converter-xslt-deserialize - The URL of the xsl stylesheet for
                                  deserialization.  This stylesheet must
                                  exist if the xslt plugin implementation
                                  is to be used.  It is assumed that the
                                  plug-in specified via converter-class-impl
                                  will make use of this value. 
				  -->
     
<!ELEMENT converter  (converter-display-name,
                     converter-description?,
                     converter-vendor?,
                     converter-class-impl,
		     converter-xslt-serialize?,
		     converter-xslt-deserialize?,
                     converter-target+)>

<!ATTLIST converter  type        CDATA      #REQUIRED>
<!ATTLIST converter  version     CDATA      #REQUIRED>

<!ELEMENT converter-display-name (#PCDATA)>
<!ELEMENT converter-description  (#PCDATA)>
<!ELEMENT converter-vendor       (#PCDATA)>
<!ELEMENT converter-class-impl   (#PCDATA)>
<!ELEMENT converter-xslt-serialize  (#PCDATA)>
<!ELEMENT converter-xslt-deserialize  (#PCDATA)>

<!ELEMENT converter-target       EMPTY>

<!ATTLIST converter-target type  CDATA      #REQUIRED>

=== ep-infosec/33_apache_openoffice/main/xmerge/java/htmlsoff/src/main/resources/META-INF/converter.xml
<?xml version="1.0"?>
<!--***********************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 ***********************************************************-->


<!--<!DOCTYPE converters SYSTEM "converter.dtd">-->
<converters>
    <converter type="staroffice/sxw" version="1.0">
        <converter-display-name>
            XSLT Transformation 
        </converter-display-name>
        <converter-description>
	    Converter which performs xslt transformations
        </converter-description>
        <converter-vendor>Apache OpenOffice</converter-vendor>
        <converter-class-impl>
	          org.openoffice.xmerge.converter.xml.xslt.PluginFactoryImpl
	</converter-class-impl>
	<converter-xslt-serialize>
	       sofftohtml.xsl
	</converter-xslt-serialize>
	<converter-xslt-deserialize>
	       htmltosoff.xsl
	</converter-xslt-deserialize>
        <converter-target type="text/html" />
    </converter>
</converters>
